name: movie_evertec
description: Movie app for Evertec technical test.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Graphics
  cupertino_icons: ^1.0.2
  phosphor_flutter: ^2.0.0
  animate_do: ^3.1.2

  # Packages
  flutter_riverpod: ^2.4.4
  go_router: ^12.0.0
  http: ^1.1.0
  either_dart: ^1.0.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Utils
  intl: ^0.18.1
  intl_utils: ^2.8.5
  envied: ^0.3.0+3
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  envied_generator: ^0.3.0+3
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-Light.ttf
          weight: 300

flutter_intl:
  enabled: true
  class_name: S
  main_locale: es
  arb_dir: lib/l10n
  output_dir: lib/gen

flutter_gen:
  output: lib/gen

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/images/app_icon.jpg'
  adaptive_icon_background: 'assets/images/app_icon.jpg'
  min_sdk_android: 21

flutter_native_splash:
  color: '#9FC3E7'
  image: assets/images/app_icon.jpg
  color_dark: '#9FC3E7'
  image_dark: assets/images/app_icon.jpg
  android_12:
    image: assets/images/app_icon.jpg
    icon_background_color: '#9FC3E7'
    image_dark: assets/images/app_icon.jpg
    icon_background_color_dark: '#9FC3E7'
