name: movie_evertec
description: Movie app for Evertec technical test.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Packages
  flutter_riverpod: ^2.4.4

  # Utils
  intl: ^0.18.1
  intl_utils: ^2.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-Light.ttf
          weight: 300

flutter_intl:
  enabled: true
  class_name: S
  main_locale: es
  arb_dir: lib/l10n
  output_dir: lib/gen

flutter_gen:
  output: lib/gen
